### ISSUE TITLE
Remove extra curly bracket

### ISSUE THREAD

**Issue by gregthompson27** [Jaredbru2/Jaredbru2.github.io#1]
https://github.com/Jaredbru2/Jaredbru2.github.io/blob/66c114d38c6cc2feba7a7b4ae2c50869cd837e0c/projects/bouncing-box/index.html#L80

@Jaredbru2, the error in your program is coming from an extra closing `}` that you added on line 80. If you remove that bracket everything should run as normal again.

**Comment by JoshHunter11** [comment]
@gregthompson27 Issue appears to be resolved
