### ISSUE TITLE
Complete last bouncing box TODO

### ISSUE THREAD

**Issue by gregthompson27** [Jaredbru2/Jaredbru2.github.io#2]
<h3>Feedback for todo 7</h3>

https://github.com/Jaredbru2/Jaredbru2.github.io/blob/665e3d5ad3756d6be1d626c4f71ffd1f035396ba/projects/bouncing-box/index.html#L84

@Jaredbru2, If you check your game you'll notice that the box slows down if you click it when it is moving from right to left. See [TODO 7](https://github.com/OperationSpark/bouncing-box#todo-7--fix-a-bug) for details on how to fix this bug.

**Comment by JoshHunter11** [comment]
@gregthompson27 Issue resolved
