### ISSUE TITLE
Fix Bouncing Box Bug

### ISSUE THREAD

**Issue by gregthompson27** [Jaredbru2/Jaredbru2.github.io#3]
<h3>Feedback for todo 7</h3>

https://github.com/Jaredbru2/Jaredbru2.github.io/blob/665e3d5ad3756d6be1d626c4f71ffd1f035396ba/projects/bouncing-box/index.html#L76-L85

@Jaredbru2,you still have the bug where the box slows down if you click it when it is moving from right to left.

Instead of always increasing the speed by 10, you'll sometimes want to "decrease" the speed by 10 (it should decrease when the speed is negative because subtracting from a negative gives you a larger negative value. So your code here really needs an if/else statement to check if the speed is positive or not, and then an increase or decrease to the speed in the if and else statements' code blocks.

See [TODO 7](https://github.com/OperationSpark/bouncing-box#todo-7--fix-a-bug) for more details.

**Comment by JoshHunter11** [comment]
@gregthompson27 Issue resolved
